# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      - image: node:10
    steps:
      - run:
          name: Install dependencies
          command: 'yarn install'
      - run:
          name: Run lint
          command: 'yarn lint'
